package lk.sdcms;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mindrot.jbcrypt.BCrypt;

/**
 * Diagnostic utility, not a behavioural test.
 *
 * <p>Run it to check whether the seeded password hashes are readable by
 * jBCrypt, and to print replacements generated by jBCrypt itself. Hashes
 * produced by a different BCrypt implementation are usually interchangeable,
 * but "usually" is not good enough when it is the reason nobody can log in.
 *
 * <p>Run with: mvn test -Dtest=PasswordHashTool
 */
class PasswordHashTool {

    /** Must match the values in data.sql. */
    private static final String[][] SEEDED = {
            {"admin",     "Admin@123",
             "$2a$10$6TTC6LJRWCK6toyw3XF9EexFlQAkPO6rMC5ZyEfoLrJwXyEsml8Fq"},
            {"reception", "Recep@123",
             "$2a$10$UIV.A1O5NZmq69SayM/b2O0WE3xSDSOJSkp44qDizPFeOZ.9bR6MC"},
            {"dentist1",  "Dentist@123",
             "$2a$10$9xWVUyZY6Iy/BCWlnA590.kdYhdET4qFCG6EBfUZRPlxNODjR5Kmi"}
    };

    @Test
    @DisplayName("Report whether the seeded hashes verify, and print replacements")
    void diagnoseAndRegenerate() {

        System.out.println();
        System.out.println("=== Checking the hashes currently in data.sql ===");

        boolean allGood = true;

        for (String[] row : SEEDED) {
            String username  = row[0];
            String password  = row[1];
            String storedHash = row[2];

            boolean verifies;
            String note = "";
            try {
                verifies = BCrypt.checkpw(password, storedHash);
            } catch (IllegalArgumentException e) {
                verifies = false;
                note = "  (jBCrypt rejected the hash format: " + e.getMessage() + ")";
            }

            System.out.printf("%-10s %s%s%n",
                    username, verifies ? "OK" : "FAILS", note);

            if (!verifies) allGood = false;
        }

        System.out.println();

        if (allGood) {
            System.out.println("All seeded hashes verify. If login still fails, the");
            System.out.println("problem is elsewhere — check that the username typed");
            System.out.println("matches exactly, and that failed_attempts is 0.");
        } else {
            System.out.println("One or more hashes are unusable by jBCrypt.");
        }

        System.out.println();
        System.out.println("=== Replacement hashes generated by jBCrypt ===");
        System.out.println("Run these against sdcms_db to be certain:");
        System.out.println();

        for (String[] row : SEEDED) {
            String password = row[1];
            String fresh = BCrypt.hashpw(password, BCrypt.gensalt(10));

            // Prove the freshly generated hash round-trips before printing it.
            if (!BCrypt.checkpw(password, fresh)) {
                throw new AssertionError("jBCrypt failed to verify its own output");
            }

            if (row[0].equals("dentist1")) {
                System.out.printf(
                        "UPDATE users SET password_hash = '%s', failed_attempts = 0,"
                        + " locked_until = NULL WHERE username LIKE 'dentist%%';%n",
                        fresh);
            } else {
                System.out.printf(
                        "UPDATE users SET password_hash = '%s', failed_attempts = 0,"
                        + " locked_until = NULL WHERE username = '%s';%n",
                        fresh, row[0]);
            }
        }

        System.out.println();
        System.out.println("Passwords remain: Admin@123 / Recep@123 / Dentist@123");
        System.out.println();
    }
}
